"""Durable persistence adapters for CeutIA decision audit and outcomes."""
from __future__ import annotations

from dataclasses import asdict
import json
import sqlite3
from typing import Mapping

from .control_plane import DecisionAuditEvent, DecisionOutcome, HumanDecisionReview


class SQLiteDecisionStore:
    """Append-only SQLite store for decision audit, review and outcome records.

    The schema stores canonical JSON payloads while preserving the immutable
    event hash chain generated by ``DecisionAuditChain``.
    """

    def __init__(self, path: str) -> None:
        self.connection = sqlite3.connect(path)
        self.connection.execute("PRAGMA journal_mode=WAL")
        self.connection.execute("PRAGMA foreign_keys=ON")
        self.connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS decision_audit (
                event_id TEXT PRIMARY KEY,
                decision_id TEXT NOT NULL,
                event_type TEXT NOT NULL,
                payload_json TEXT NOT NULL,
                previous_hash TEXT NOT NULL,
                event_hash TEXT NOT NULL UNIQUE,
                timestamp TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_decision_audit_decision
                ON decision_audit(decision_id, timestamp);
            CREATE TABLE IF NOT EXISTS decision_reviews (
                review_id TEXT PRIMARY KEY,
                decision_id TEXT NOT NULL,
                payload_json TEXT NOT NULL,
                timestamp TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS decision_outcomes (
                decision_id TEXT PRIMARY KEY,
                option_id TEXT NOT NULL,
                payload_json TEXT NOT NULL,
                outcome_at TEXT NOT NULL
            );
            """
        )
        self.connection.commit()

    def append(self, event: DecisionAuditEvent) -> None:
        self.connection.execute(
            "INSERT INTO decision_audit(event_id,decision_id,event_type,payload_json,previous_hash,event_hash,timestamp) VALUES(?,?,?,?,?,?,?)",
            (event.event_id, event.decision_id, event.event_type,
             json.dumps(dict(event.payload), sort_keys=True, default=str),
             event.previous_hash, event.event_hash, event.timestamp),
        )
        self.connection.commit()

    def events(self, decision_id: str) -> tuple[DecisionAuditEvent, ...]:
        rows = self.connection.execute(
            "SELECT event_id,decision_id,event_type,payload_json,previous_hash,event_hash,timestamp FROM decision_audit WHERE decision_id=? ORDER BY timestamp,event_id",
            (decision_id,),
        ).fetchall()
        return tuple(DecisionAuditEvent(r[0], r[1], r[2], json.loads(r[3]), r[4], r[5], r[6]) for r in rows)

    def record_review(self, review: HumanDecisionReview) -> None:
        self.connection.execute(
            "INSERT INTO decision_reviews(review_id,decision_id,payload_json,timestamp) VALUES(?,?,?,?)",
            (review.review_id, review.decision_id, json.dumps(asdict(review), sort_keys=True), review.timestamp),
        )
        self.connection.commit()

    def record_outcome(self, outcome: DecisionOutcome) -> None:
        self.connection.execute(
            "INSERT OR REPLACE INTO decision_outcomes(decision_id,option_id,payload_json,outcome_at) VALUES(?,?,?,?)",
            (outcome.decision_id, outcome.option_id, json.dumps(asdict(outcome), sort_keys=True), outcome.outcome_at),
        )
        self.connection.commit()

    def outcome(self, decision_id: str) -> DecisionOutcome | None:
        row = self.connection.execute(
            "SELECT payload_json FROM decision_outcomes WHERE decision_id=?", (decision_id,)
        ).fetchone()
        if row is None:
            return None
        payload = json.loads(row[0])
        return DecisionOutcome(**payload)

    def verify_chain(self, decision_id: str) -> bool:
        previous = "GENESIS"
        for event in self.events(decision_id):
            canonical = json.dumps(dict(event.payload), sort_keys=True, default=str, separators=(",", ":"))
            import hashlib
            expected = hashlib.sha256(f"{previous}|{event.event_id}|{canonical}".encode()).hexdigest()
            if event.previous_hash != previous or event.event_hash != expected:
                return False
            previous = event.event_hash
        return True

    def close(self) -> None:
        self.connection.close()


__all__ = ["SQLiteDecisionStore"]
